django_book/books/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

urlpatterns = [
    url('^$', views.index, name='index'),
    url('^study/$', views.study, name='study'),
    url('^study/dark/$', views.dark, name='dark'),
    url('^info/$', views.info, name='info'),
    url('^live/$', views.live, name='live'),
    url('^why/$', views.why, name='why'),
    url('^test/$', views.test, name='test'),
    url('^451/$', views.f451, name='451'),
    url('^1984/$', views.bigbrother, name='1984'),
    url('^bbs/$', views.bbs, name='bbs'),
    url('^ai/$', views.ai, name='ai'),
    url(r'^ai/\d+/$', views.hello, name='hello'),
    url('^crypto/$', views.crypto, name='crypto'),
    url('^decrypto/$', views.decrypto, name='decrypto'),
    url('^get_key/$', views.get_key, name='get_key'),
    url('^crypto_lv2/$', views.crypto_lv2, name='crypto_lv2'),
    url('^hidden/$', views.hidden, name='hid'),
    url("^filter/$", views.filter, name="filter"),
    url("^ftp/$", views.ftp, name='ftp'),
    url("^404/$", views.page404),
    url("^youtube/$", views.youtube, name='youtube'),
    url('^attack/$', views.attack, name='attack'),
    url('^mirror/$', views.mirror, name='mirror'),
]

django_book/django_book/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(('books.urls', 'books'), namespace='books')),
]

django_book/books/models.py
from django.db import models

# Create your models here.

django_book/books/forms.py
#!/usr/bin/env python

from django import forms


class BookForm(forms.Form):
    text = forms.CharField(label="内容", required=True, max_length=4000)


class CryptoForm(forms.Form):
    text = forms.CharField(required=False, max_length=4000)
    key = forms.CharField(required=True, max_length=100)
    crypto_text = forms.CharField(required=False, max_length=4000)

django_book/books/views.py
# /usr/bin/env python
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.http import HttpResponse

from .forms import BookForm, CryptoForm
from .ai import fake_ai
from .word import word, read_site, hidden_site, random_index_html
from .crypto import getRandomKey, MonoAlphabeticCipher
from .crypto2 import encrypt_oracle, decrypt_oralce
from .ftp import show_files_info


def index(request):
    msg = word()
    content = {'msg': msg}
    index_html = random_index_html()
    return render(request, index_html, content)


def study(request):
    content = read_site()
    return render(request, 'study.html', content)


def info(request):
    return render(request, 'info.html')


def live(request):
    return render(request, 'live.html')


def why(request):
    return render(request, 'why.html')


def test(request):
    content = {
        'text0': request.META['CONTENT_LENGTH'],
        'text1': request.META['CONTENT_TYPE'],
        'text2': request.META['HTTP_ACCEPT'],
        'text3': request.META['HTTP_ACCEPT_ENCODING'],
        'text4': request.META['HTTP_ACCEPT_LANGUAGE'],
        'text5': request.META['HTTP_HOST'],
        'text6': request.META['HTTP_USER_AGENT'],
        'text7': request.META['QUERY_STRING'],
        'text8': request.META['REMOTE_ADDR'],
        'text9': request.META['REMOTE_HOST'],
        'text10': request.META['REQUEST_METHOD'],
        'text11': request.META['SERVER_NAME'],
        'text12': request.META['SERVER_PORT'],
    }
    return render(request, 'test.html', content)


def f451(request):
    return render(request, './../../django_book/templates/451.html', status=451)


def bigbrother(request):
    content = hidden_site()
    return render(request, 'bigbrother.html', content)


def bbs(request):
    return render(request, 'bbs.html')


def ai(request):
    if request.method != 'POST':
        form = BookForm()
        return render(request, 'ai.html', {'form': form})
    else:
        form = BookForm(request.POST)
        if form.is_valid():  # 验证表单数据
            msg = form.cleaned_data['text']  # 获取验证后的表单数据
            f = fake_ai(msg)
            content = {'f': f, 'msg': msg}
            return render(request, 'ai.html', content)
        else:
            return render(request, 'ai.html', {'form': form})


def crypto(request):
    if request.method != 'POST':
        return render(request, 'crypto.html')
    else:
        form = CryptoForm(request.POST)
        if form.is_valid():
            text = form.cleaned_data['text']
            c_key = form.cleaned_data['key']
            mode = 'encrypt'
            eptext = MonoAlphabeticCipher(c_key, text, mode).get('translated')
            if eptext:
                content = {'eptext': eptext}
            else:
                text = "不正确的密钥！"
                content = {'c_key_error': text}
            return render(request, 'crypto.html', content)
        else:
            text = "不允许为空!"
            content = {'error': text}
            return render(request, 'crypto.html', content)


def decrypto(request):
    if request.method != 'POST':
        return render(request, 'crypto.html')
    else:
        form = CryptoForm(request.POST)
        if form.is_valid():
            eptext = form.cleaned_data['text']
            c_key = form.cleaned_data['key']
            mode = 'decrypt'
            text = MonoAlphabeticCipher(c_key, eptext, mode).get('translated')
            if text:
                content = {'text': text}
            else:
                text = '不正确的密钥！'
                content = {'key_error': text}
            return render(request, 'crypto.html', content)

        else:
            text = "不允许为空！"
            content = {'d_error': text}
            return render(request, 'crypto.html', content)


def get_key(request):
    if request.method != 'POST':
        key = getRandomKey()
        content = {'key': key}
        return render(request, 'crypto.html', content)


def crypto_lv2(request):
    if request.method != 'POST':
        return render(request, 'crypto2.html')
    else:
        form = CryptoForm(request.POST)
        if form.is_valid():
            text = form.cleaned_data['text']  # 获取密文
            key = form.cleaned_data['key']  # 获取密钥
            crypto_text = form.cleaned_data['crypto_text']  # 获取密文

            if text and key:  # 如果存在明文和密钥, 则做加密, 如果三者都存在优先做加密
                serverMsg = encrypt_oracle(key, text).get('translated')
                if serverMsg:  # 密钥正确返回密文
                    content = {'serverMsgCT': serverMsg}
                else:  # 密钥错误, 返回空字典
                    content = {'error': '密钥不正确!'}

            elif crypto_text and key:  # 如果存在密文和明文, 则做解密
                serverMsg = decrypt_oralce(key, crypto_text).get('translated')
                if serverMsg:
                    content = {'serverMsgT': serverMsg}
                else:
                    content = {'error': '密钥不正确!'}

            else:  # 其他情况, 只输入了密钥, 返回错误信息
                content = {'error': '缺少明文或密文!'}
            return render(request, 'crypto2.html', content)

        else:  # 验证失败
            text = "密钥为空! 或长度超出限制!"
            content = {'error': text}
            return render(request, 'crypto2.html', content)


def hidden(request):
    return render(request, 'hidden.html')


def filter(request):
    return render(request, 'filter.html')


def hello(request):
    return HttpResponse("Congratulations!<br>You found this!<br><br>The answer is <b>42</b>.<br>")


def dark(request):
    return render(request, 'dark.html')


def ftp(request):
    content = show_files_info()
    return render(request, 'ftp.html', content)


def page404(request):
    # return render(request, "./../../django_book/templates/404.html")
    return render(request, "404.html")


def youtube(request):
    return render(request, "youtube.html")


def attack(request):
    return render(request, 'attack.html')


def mirror(request):
    content = (
        ('Google', 'go.littlepotato.life', 'WorkersProxy'),
        ('Google', 'google.littlepotato.life', 'NginxGoogle'),
        ('Google Drive', 'drive.littlepotato.life', 'GoIndex'),
        ('Wikipedia', 'wiki.littlepotato.life', 'WorkersProxy'),
        ('YouTube', 'bot-yt-1.herokuapp.com', 'You2Php'),
        ('WebProxy', 'proxy.littlepotato.life', 'JsProxy'),
        ('WebProxy', 'bot-go-2.herokuapp.com', 'NodeUnblocker'),
    )

    return render(request, 'mirror.html', {'content': content})

django_book/books/templates/attack.html
{% extends "base.html" %}

{% block content %}
    <iframe width="640" height="640" src="https://cybermap.kaspersky.com/cn/widget/dynamic/dark" frameborder="0">
    </iframe>
{% endblock content %}

django_book/books/templates/bigbrother.html
{% extends 'base.html' %}

{% block header %}
        <div class="jumbotron" style="text-align:center">
            <h4>自由就像空氣</h4>
            <h4>你只會在窒息時</h4>
            <h4>才會察覺它的存在</h4>
        </div>
{% endblock header %}

{% block content %}
    <!-- <p style="text-align:center">
        <small>
        那不能杀死我的，使我更强。<br>
        What does NOT kill me, makes me stronger.
        </small>
    </p>
  <br>
  <br>
  <br> -->
    <h3>V2Ray</h3>
    <i>Project V 的核心工具称为V2Ray，其主要负责网络协议和功能的实现，与其它 Project V 通信。V2Ray 可以单独运行，也可以和其它工具配合，以提供简便的操作流程。
    </i><br>
    <br>
    <p>
        <b>V2RayN 绿色版</b>(Windows)<br>
        <a href="/static/pdf/1984.7z">本地下载</a> | <a href="https://github.com/2dust/v2rayN/releases">Github</a><br>
        <b>V2Ray-core</b>(Linux|macOS|Windows)<br>
        <small>*以命令行方式启动, 不推荐小白使用.</small>
        <br>
        <a href="https://github.com/v2ray/v2ray-core/releases">Github</a><br>
        <b>BifrostV</b>(Android)<br>
        <a href="/static/pdf/com.github.dawndiy.bifrostv_0.6.8_[apkleecher.com].apk">本地下载</a> |
        <a href="https://play.google.com/store/apps/details?id=com.github.dawndiy.bifrostv">Play Store</a> | <a
            href="https://apkpure.com/bifrostv/com.github.dawndiy.bifrostv">APK Pure</a><br>
        <b>Quantumult</b>(iOS)<br>
        <a href="https://itunes.apple.com/hk/app/quantumult/id1252015438?mt=8">iTunes</a><br>
        <b>Shadowrocket</b>(iOS)<br>
        <a href="https://itunes.apple.com/hk/app/shadowrocket/id932747118?mt=8">iTunes</a><br>
    </p>
    <br>
    <h3>Tor Browser</h3>
    <i>Tor是实现匿名通信的自由软件。Tor的设计原意在于保障用户的个人隐私，以及不受监控地进行秘密通信的自由和能力。</i>
    <br>
    <br>
    <p>
        <b>Tor 安装版</b>(Windows)<br>
        <a href='/static/pdf/torbrowser-install-win64-8.0.3_zh-CN.exe'>本地下载</a> | <a
            href="https://www.torproject.org/download/">官网下载</a><br>
        <b>Tor 绿色版</b>(Windows)<br>
        <a href='/static/pdf/Tor Browser.rar'>本地下载</a><br>
    </p>
    <br>
    <h3>保护隐私</h3>
    <i>在这样的时代背景下，专制的势力（政府、商业公司）必定会利用信息技术来强化对个人的奴役；反之，个人也可以利用信息技术来捍卫自由，反抗奴役。</i>
    <br>
    <br>
    {% for site_name, site_url in content %}
        <li style="list-style-type: none;">
            <a href="{{ site_url }}">{{ site_name }}</a>
        </li>
    {% endfor %}
    <br>
{% endblock content %}

django_book/books/templates/ftp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ftp server</title>
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <style>
        a:link {
            text-decoration: none;
            color: blue
        }

        #label1 {
            width: 100%;
            float: left;
        }

        #li1 {
            list-style-type: none;
        }

        #span1 {
            width: 17%;
            float: left;
            display: block;
        }

        #span2 {
            width: 18%;
            float: left;
            display: block;
        }

        #a1 {
            width: 65%;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
            display: block;
            float: left;
        }

        #btn1 {
            width: 100px;
            background-color: lightskyblue;
            border: none;
            padding: 1px;
            line-height: 38px;
            color: white;
            font-size: 16px;
            margin: 0px;
            border-radius: 25px;
        }

        /* 手机版样式 */
        @media screen and (max-device-width: 767px) {

            #span1 {
                display: none;
            }

            #span2 {
                display: none;
            }
        }
    </style>
</head>
<body>
<button class="btn1" id="btn1"
        onclick="window.location.href='{% url 'books:info' %}'">返回
</button>
<h4>Django 文件传输 V1.0</h4>
<hr>
<div>
    <label id="label1">
        {% for file_name, file_time, file_size in content %}
            <li id="li1">
                <a id="a1" href="/static/pdf/share/{{ file_name }}" download="">{{ file_name }}</a>
                <span id="span1">{{ file_size }}</span>
                <span id="span2">{{ file_time }}</span>
            </li>
        {% endfor %}
    </label>
</div>
</body>
</html>

django_book/books/templates/hidden.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="refresh" content="3;URL=/static/pdf/hidden.txt">
</head>
<body>
<i>仅用于学习交流使用。须遵守当地法律法规， 请于下载后24小时内删除。</i>
<br>
<i>页面将在3秒后跳转。</i>
</body>
</html>

django_book/books/templates/index_1.html
{%  extends "base.html" %}

{% block header %}
  <div class="jumbotron">
      <h4>{{ msg }}</h4>
  </div>
{% endblock header %}

{% block content %}

    <audio controls="controls">
        <source src="/static/pdf/EveryStar.mp3" type="audio/mp3" >
        Your browser does not support the audio element.
    </audio>


    <xmp>
    當每顆星星 Every Star

    當一顆星 擱淺人間 再不能回 曾經的天際線
    遙遠誓言 不如謊言 飲鴆片刻 片刻給我安慰

    那失眠無垠了黑夜
    任黑夜豢養著思念
    讓思念模糊了雙眼 OH⋯

    當每顆星星都在嗚咽 都在落淚
    每個幻想 都已幻滅
    是否能相信 妳會出現？

    當一顆星 流浪千年 祈禱萬遍 會不會有個誰
    百轉千迴 帶我逃脫 無盡試煉 無謂荒蕪歲月

    那三月綻放了誓言
    在四月遺落了謊言
    而五月我依然眷戀 OH⋯

    當每顆星星都在嗚咽 都在落淚
    每個幻想 都已幻滅
    是否能相信 妳會出現？

    那三月綻放了誓言
    在四月遺落了謊言
    而五月我依然眷戀 OH⋯

    當每顆星星都在嗚咽 都在落淚
    每個幻想 都已幻滅
    是否能相信 會有妳 的出現？

    當每顆星星都在嗚咽 都在落淚
    每個幻想 都已幻滅
    依然相信 會有妳出現
    OH⋯ OH⋯
    </xmp>

    <br>
{% endblock content %}

django_book/books/templates/index_2.html
{%  extends "base.html" %}

{% block header %}
  <div class="jumbotron">
      <h4>{{ msg }}</h4>
  </div>
{% endblock header %}

{% block content %}

    <audio controls="controls">
        <source src="/static/pdf/HalfALife.mp3" type="audio/mp3" >
        Your browser does not support the audio element.
    </audio>


    <xmp>
    一半人生 Half a Life

    在某個清晨 回望我一生
    活得雖認真 卻微小如塵
    想要唱首歌 去唱哭別人
    最後卻是我 滿臉淚痕

    早告別青春 活成了別人
    經歷的時代 已如此陌生
    年少時的話 又不敢承認
    低頭在人海 浮浮沉沉

    我的一半人生 飄盪就像只風箏
    如果命運是風 什麼又是我的繩
    我的一半人生 冷暖就讓我自己過問
    有熱愛有恨 有未知的前程

    在某個清晨 回望我一生
    活得雖認真 卻微小如塵
    想要唱首歌 去唱哭別人
    最後卻是我 滿臉淚痕

    早告別青春 活成了別人
    經歷的時代 已如此陌生
    年少時的話 又不敢承認
    低頭在人海 浮浮沉沉

    我的一半人生 飄盪就像只風箏
    如果命運是風 什麼又是我的繩
    我的一半人生 冷暖就讓我自己過問
    有熱愛有恨 有未知的前程

    我的一半人生 飄盪就像只風箏
    如果命運是風 什麼又是我的繩
    我的一半人生 冷暖就讓我自己過問
    有熱愛有恨 有未知的前程
    有熱愛有恨 有未知的前程
    </xmp>

    <br>
{% endblock content %}

django_book/books/templates/index_5.html
{%  extends "base.html" %}

{% block header %}
  <div class="jumbotron">
      <h4>{{ msg }}</h4>
  </div>
{% endblock header %}

{% block content %}

    <audio controls="controls">
        <source src="/static/pdf/Undertale.mp3" type="audio/mp3" >
        Your browser does not support the audio element.
    </audio>


    <xmp>
    地下传说 Undertale

    很久很久以前, 有个人类掉进了遗迹.
    那人类摔伤了, 于是呼喊求救.

    国王的儿子, 艾斯利尔, 听见了人类的呼救.
    他把这个人类带回了城堡.

    慢慢地, 艾斯利尔和这个人类变得情同手足.
    国王和王后也将这个人类小孩视如己出.
    地下世界充满了希望.

    然后... 有一天...
    这个人类得了很重的病.

    身患重病的人类只有一个请求.
    想看看自己故乡村庄的花.
    但我们却无能为力.

    第二天.
    第二天.
    ...
    这个人类死去了.

    艾斯利尔悲痛欲绝, 吸收了这个人类的灵魂.
    他化作了一个无比强大的存在.

    借由人类的灵魂, 艾斯利尔得以穿过结界.
    他抱着人类的遗体, 走进了落日的余晖之中.
    并回到这个人类生活过的村庄.

    艾斯利尔走到了村子中心.
    在那里, 他找到一片开满金色鲜花的花圃.
    他抱着人类走进花圃.

    突然间, 传来了尖叫声.
    村民们看到了抱着人类遗体的艾斯利尔.
    他们认为是他杀死了这个小孩.

    人类用尽所能攻击艾斯利尔.
    他遭受了暴风骤雨般的猛烈攻势.
    艾斯利尔拥有的力量足以将他们尽数消灭.

    但是...
    艾斯利尔没有还手.
    艾斯利尔牢牢抱着人类的遗体...
    带着微笑缓缓的离开了.

    伤痕累累的艾斯利尔蹒跚地回到了家.
    他走进了城堡, 然后瘫倒在地.
    化作一团尘埃, 飘散在整个花园里.

    地下王国陷入了绝望.
    国王和王后在一夜之间, 失去了两个孩子.
    人类再一次夺走了我们的一切.

    国王决定, 是时候终结我们的痛苦了.
    必须杀死每一个坠入地下世界的人类.
    有了足够的灵魂, 我们就可以将结界彻底摧毁.

    那一刻已经不远了.
    |||艾斯戈尔国王
      会带我们走出地下.
      会给我们希望.
      会拯救我们大家.

    你也应该露出微笑.
    你难道不兴奋吗?
    你难道不高兴吗?

    你终于可以自由了.
    </xmp>
    <img src="/static/pdf/hope.png" alt="hope" width="50%" height="50%">
    <br>
    <br>
{% endblock content %}

django_book/books/templates/index_6.html
{% extends "base.html" %}

{% block header %}
    <div class="jumbotron">
        <h4>{{ msg }}</h4>
    </div>
    <style>
        img {
            border: 0;
            display: inline;
        }
    </style>
{% endblock header %}

{% block content %}

    <audio controls="controls">
        <source src="/static/pdf/battlefield4.mp3" type="audio/mp3">
        Your browser does not support the audio element.
    </audio>
    <br>
    <img src="/static/pdf/battlefield4.jpg" width="50%" height="50%"><img src="/static/pdf/battlefield4_2.jpg" width="50%" height="50%"><img src="/static/pdf/battlefield4_3.jpg" width="50%" height="50%"><img src="/static/pdf/battlefield4_4.jpg" width="50%" height="50%">
    <br>
    <br>
{% endblock content %}

django_book/books/templates/info.html
{% extends 'base.html' %}

{% block header %}
    <style type="text/css">
        .divcss5 {
            border: 1px solid #FFF;
            width: 600px
        }
    </style>
    <div class="jumbotron">
        <h4>The unexamined life is not worth living.</h4>
    </div>
{% endblock header %}

{% block content %}
    <ul>
        <li><h4><a href="https://search.littlepotato.life">土豆搜索</a></h4></li>
        <li><h4><a href="https://drive.littlepotato.life">我的网盘</a></h4></li>
        <li><h4><a href="{% url 'books:mirror' %}">镜像站点</a></h4></li>
        <li><h4><a href="{% url 'books:ai' %}">Lucy(beta)</a></h4></li>
        <li><h4><a href="{% url 'books:crypto_lv2' %}">文本加密</a></h4></li>
        <li><h4><a href="https://note.littlepotato.life/">笔记本</a></h4></li>
        <li><h4><a href="{% url "books:attack" %}">实时网络攻击</a></h4></li>
        <li><h4><a href='{% url "books:live" %}'>国际空间站直播画面(需翻墙)</a></h4></li>
        <li><h4><a href='https://www.16personalities.com/ch/%E4%BA%BA%E6%A0%BC%E6%B5%8B%E8%AF%95'>MBTI 16种人格测试</a></h4></li>
    </ul>
    <br>
{% endblock content %}

django_book/books/templates/mirror.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>mirror</title>
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <style>
        a:link {
            text-decoration: none;
        }

        #btn1 {
            width: 60px;
            background-color: lightskyblue;
            border: none;
            padding: 1px;
            line-height: 30px;
            color: white;
            font-size: 16px;
            margin: 0px;
            border-radius: 15px;
        }

        .title {
            text-align: center;
        }

        .table {
            width: 100%;
        }

        .th1, .th3 {
            width: 30%;
        }

        .th2 {
            width: 40%;
        }

        .td1, .td3 {
            width: 30%;
            text-align: center;
        }

        .td2 {
            width: 40%;
            text-align: center;
        }

        .a1 {
            color: gray;
        }

        .a2 {
            color: green;
        }
    </style>
</head>
<body>
<button class="btn1" id="btn1"
        onclick="window.location.href='{% url 'books:info' %}'">返回
</button>
<h2 class="title">Mirror Sites</h2>
<hr>
<div>
    <table class="table">
        <tr>
            <th class="th1">Name</th>
            <th class="th2">Mirror</th>
            <th class="th3">Technology</th>
        </tr>
        {% for x, y, z in content %}
            <tr>
                <td class="td1">{{ x }}
                </td>
                <td class="td2"><a class="a2" href="https://{{ y }}">{{ y }}</a>
                </td>
                <td class="td3">{{ z }}</td>
            </tr>
        {% endfor %}
    </table>
</div>
</body>
</html>

django_book/books/templates/redirect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>302</title>
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="refresh" content="1;URL=https://search-books.herokuapp.com/">
</head>
<body>
正在唤醒应用, 请稍后....
</body>
</html>

django_book/books/templates/why.html
{% extends 'base.html' %}

{% block header %}
    <div class="jumbotron">
        <h4>Stay Hungry. Stay Foolish.</h4>
    </div>
{% endblock header %}

{% block content %}

    <div style="text-align:center">
        <!-- <h3>首先，你应该对英文读写没什么问题!</h3>
         <p>
         为什么这么说? 逻辑是这样的, 如果你上了 Google 还是在用中文关键词, 那么你科学上网有什么意义呢? 换言之, 科学上网的目的是为了进入广阔的世界范围与全世界的人交流, 所以, 英文是必备的, 如果你英文有问题, VPN 过去的用处也不大. <br>
         所以, 我把这个前提条件放在第一的位置, 就是说—— 真正的墙不是 GFW, 而是人的大脑! &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;by&nbsp;左耳朵·科学上网
         </p> -->
        <!-- 想帶你們去那些地方走走。【冏星人】
        <video width="100%" height="100%" controls="controls" >
            <source src="/static/pdf/MyStory.MP4" type="video/mp4" />
        </video>
        <br>
        <br>
        <br>
        UNBROKEN<br>
        <a href="https://jj5cm.herokuapp.com/watch.php?v=26U_seo0a1g">点击播放</a>
        -->
        <h3>你到底在等什麼？！| 加里·維納查克吐槽</h3>
        <video width="80%" height="80%" controls="controls">
            <source src="/static/pdf/WAYW.mp4" type="video/mp4"/>
        </video>
        <br>
        <br>
    </div>
{% endblock content %}

django_book/books/templates/youtube.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>302</title>
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="refresh" content="1;URL=https://bot-yt-1.herokuapp.com/">
</head>
<body>
正在唤醒休眠中应用, 可能需要 5-10 秒, 请耐心等待...
</body>
</html>

django_book/django_book/templates/451.html
{% extends "base.html" %}

{% block header %}
    <meta http-equiv="refresh" content="7;URL=/1984/">
    <h3>
        <small>
            451 Unavailable For Legal Reasons<br>
            应有关部门要求，根据相关法律、法规，网页未予显示。
        </small>
    </h3>
{% endblock header %}

{% block content %}
    <div style="width: 70%">
        <p>
            <i>
                <font size="4">
                    "等战争结束, 总会有那么一天, 一年;
                    我们可以重新写出这些书. 把那些人一个个找来, 背诵他们记得的知识, 再把那些知识付梓成书,
                    直到另一个黑暗时代来临, 届时我们或许得从头再玩一遍这把戏.
                    但这也正是人类的奇妙之处, 人类绝不会消沉厌弃到放弃从头来过的地步,
                    因为他非常明白这样做是重要的, 值得的."
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;—「华氏 451」
                </font>
            </i>
        </p>
    </div>
{% endblock content %}